#!/bin/bash

# Build
echo "Building Project..."
./scripts/build

# Truncate output files
> bin/output.out
> bin/stats.out

# Spawn processes
for i in dc02 dc03 dc06 dc05 dc10 dc09 dc15 dc18 dc23
do
    ( ./scripts/run "$i" & )
done
