#!/bin/bash

# Build
echo "Building Project..."
./scripts/build

# Truncate output file
> bin/output.out

# Spawn processes
for i in dc02 dc03 dc06
do
    ( ssh $(whoami)@"$i".utdallas.edu ./aos-pgms/project2/scripts/run )
done
